arch:
  - amd64
  - ppc64le
language: python
sudo: false
addons:
  apt:
    packages:
      - libgnutls-dev


cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.11-dev
  - pypy3
  - pypy3.6
  - pypy3.7

services:
  - mysql
  - postgresql

env:
  global:
    - TEST_DB_HOST=localhost
    - TEST_MYSQL_USER=root
    - TEST_POSTGRES_USER=postgres

matrix:
  allow_failures:
    - python: pypy3

install:
  - pip install tox tox-travis coveralls

script:
  - tox

after_success:
  - coveralls
