language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy3

services:
  - mysql
  - postgresql

env:
  global:
    - TEST_DB_HOST=localhost
    - TEST_MYSQL_USER=root
    - TEST_POSTGRES_USER=postgres
  matrix:
    - TOX_ENV=py35
    - TOX_ENV=py36
    - TOX_ENV=py37
    - TOX_ENV=py38
    - TOX_ENV=pypy3

matrix:
  allow_failures:
    - python: pypy3
      env: TOX_ENV=pypy3
  include:
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.8
      env: TOX_ENV=py38
    - python: pypy3
      env: TOX_ENV=py33

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
