---
name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    # container:
    #   image: debian:bullseye
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      mysql:
        image: mysql:latest
        env:
          MYSQL_USER: mysql
          MYSQL_PASSWORD: password
          MYSQL_RANDOM_ROOT_PASSWORD: true
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    env:
      TEST_MYSQL_HOST: mysql
      TEST_MYSQL_USER: mysql
      TEST_MYSQL_PASSWORD: password
      TEST_POSTGRES_HOST: postgres
      TEST_POSTGRES_USER: postgres
      TEST_POSTGRES_PASSWORD: password
    strategy:
      matrix:
        python-version:
          # - 3.5
          # - 3.6
          # - 3.7
          # - 3.8
          - 3.9
          # - "3.10"
          # - 3.11-dev
          # - pypy3.6
          # - pypy3.7
          # - pypy3.8
    steps:
      - run: >-
          sudo apt update
          && sudo apt install --yes libcurl4-openssl-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install wheel
      - run: pip install -r dev-requirements.txt
      - run: pip install .
      - run: coverage run -m unittest openid.test.test_suite
      - run: coverage report
